### ISSUE TITLE
Two problems in GameSolver

### ISSUE THREAD

**Issue by jbrucker** [OOP2018/guessing-game-5710546186#2]
First issue is the contrived message "I think of "...
Its not GameSolver's job to create messages.  The NumberGame does that.
AND GameSolver isn't supposed to print anything.

The major issue is:  your test for solving the game
is based on testing the text of getMessage.
You should use the return value of game.guess()!

**Comment by 5710546186** [comment]
"The major issue is: your test for solving the game
is based on testing the text of getMessage.
You should use the return value of game.guess()!"

Do you mean the verify answer part in Main Class?
But I've already use game.guess() to check that.
